name: GitHub Schedule Hugo Posts
on:
  push:
    branches:
    - master
  schedule:
    - cron: '*/3 * * * *' # Once per day at 05.15hr
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is to schedule hugo posts on freerbeing website"
      - run: hugo
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been updated"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
