name: GitHub Schedule Hugo Posts
on:
  schedule:
    - cron: '*/3 * * * *' # Once per day at 05.15hr
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Netlify
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        - run: echo "üçè This schedule job's status is ${{ job.status }}."
        env:
          TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
